import type { Metadata } from 'next';

/**
 * Canonical site identity, used by every route's metadata and by sitemap.ts.
 *
 * Every page previously inherited the root layout's title and description, so
 * a production build served `<title>16 Bit Mahjong</title>` and the same
 * description on ~70 URLs with zero canonical tags. Google collapses
 * near-identical pages, which is why 56 lessons of real content were not
 * ranking: they all looked like one page.
 */

/**
 * Absolute origin. Vercel exposes the deployment host without a scheme, so
 * previews get their own canonical rather than pointing at production —
 * otherwise every preview would claim to be the live site.
 */
const RAW_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL
  ?? (process.env.VERCEL_ENV === 'production'
    ? 'https://16bitmahjong.co'
    : process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : 'https://16bitmahjong.co');

/**
 * Normalised once, here, because every consumer concatenates onto it: a
 * trailing slash from an env var would produce `//learn` in the sitemap and a
 * malformed metadataBase, and a scheme-less host (which is how Vercel exposes
 * VERCEL_URL) is not a valid absolute URL at all.
 */
export const SITE_URL = (
  /^https?:\/\//.test(RAW_SITE_URL) ? RAW_SITE_URL : `https://${RAW_SITE_URL}`
).replace(/\/+$/, '');

export const SITE_NAME = '16 Bit Mahjong';

/** Appended by Next via the root layout's title.template. */
export const TITLE_SUFFIX = ` — ${SITE_NAME}`;

/**
 * Social card, generated by `app/opengraph-image.tsx`.
 *
 * Referenced explicitly rather than relying on Next's file convention: any
 * route that defines its own `openGraph` block REPLACES the parent's, which
 * drops the file-based image. Every page here sets openGraph for its title, so
 * without this the card rendered with no image at all — verified by curl,
 * which showed og:title and og:description present and og:image absent while
 * /opengraph-image itself returned a valid 200 PNG.
 */
export const OG_IMAGE = '/opengraph-image';

/**
 * Build a page's metadata with a canonical URL.
 *
 * `path` is root-relative and becomes the canonical, which is the half that
 * actually resolves duplicate-content ambiguity; a unique title alone does not.
 */
export function pageMetadata({
  title,
  description,
  path,
  noindex = false,
}: {
  title: string;
  description: string;
  /**
   * Root-relative canonical. Omit for dynamic routes that have no single
   * canonical instance — emitting a path with a literal `[param]` segment
   * would advertise a URL that does not exist.
   */
  path?: string;
  noindex?: boolean;
}): Metadata {
  return {
    title,
    description,
    ...(path ? { alternates: { canonical: path } } : {}),
    openGraph: {
      title: `${title}${TITLE_SUFFIX}`,
      description,
      ...(path ? { url: path } : {}),
      siteName: SITE_NAME,
      type: 'website',
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title: `${title}${TITLE_SUFFIX}`,
      description,
      images: [OG_IMAGE],
    },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };
}
